n1 = int(input('Digita um valor '))
n2 = int(input('Digite outro valor '))
print('A soma é {}'.format(n1+n2))
print('A subtração é {}'.format(n1-n2))
print('A multiplicação é {}'.format(n1*n2))
print('A divisão é {}'.format(n1/n2))
print('A resto da divisão é {}'.format(n1%n2))
print('A divisão inteira é {}'.format(n1//n2))
print('A potencia é {}'.format(n1**n2))